'''
Help file for DEERs suite.

Here you can take some knowledge about these script and... maybe... about deers.

'''

def texto():
    print()
    print("********************************************************************")
    print("DEERs HELP MENU")
    print("********************************************************************")
    print("This program has been created for analyze and/or edit data")
    print("  from rotational spectroscopy experiments. It has been")
    print("  created as results of the necesities of different type")
    print("  of experiments.")
    print()
    print("I have to aknowledge Sergio Mato's help on the conceptual")
    print("  design and for the alpha- and beta-testing.")
    print()
    print("Quick configuration info if you haven't readed the README file yet")
    print("  (you should read it ¬¬): run the precfg.py scriptand it will check")
    print("   your system and configure it if necessaty to use DEERs.")
    print()
    print("This program has different options. Here, I will briefly explain")
    print("  each script. Futher information, bug reports or any other")
    print("  consideration about the program can be made by email at")
    print("  raul.aguado@uva.es or at github.com/raul-aguado")
    print()
    print("OPTION 1: PEAK FINDING")
    print("This option allows you to detect all the points in a spectrum")
    print("  that are higher than a certain level. The minimum height of")
    print("  the peaks is 3sigma of the points in the spectrum corrected")
    print("  by a security factor that ensures the detection of real peaks")
    print("  avoiding false positives. Security factor is pre-defined as")
    print("  1.1 but can be changed; the program will detect the peaks and")
    print("  plot the spectrum, highlihting the found peaks in red. Then,")
    print("  the script will ask if the peaks have been found correctly. If")
    print("  not, you will be asked for a new security factor. The process")
    print("  will be repeated until the peaks are succesfully found.")
    print()
    print("OPTION 2: SN comparer")
    print("During our broadband FTMW experiments, data captured by the")
    print("  oscilloscope is saved with regularity (every 5k-10k adquisition).")
    print("  The SN ratio of the experiment should increase as the number of")
    print("  adquisitions does, but certain experimental conditions could lead")
    print("  to a worse SN ratio in some cases. This script will take a folder")
    print("  that contains the same experiment data but with different")
    print("  acqusition and will compare the SN for a given signal and noise.")
    print("  This helps to locate the spectrum with the better SN ratio.")
    print()
    print("OPTION 3: SEARCH FOR PEAKS IN SPECTROSCOPIC DATABASES")
    print("This script compares peaks with different spectroscopic databases")
    print("  as MADEX or CDMS (Splatalogue compatibility is coming soon).")
    print("  The input peaks can be given from a .lin file (output ")
    print("  of the ASCP program coded by Kisiel) or directly from a")
    print("  experimental spectrum. In the former case the frequencies will")
    print("  readed directly from de .lin file. Meanwhile, in the latter case,")
    print("  the peak finder script (option 1) will be used to locate peaks")
    print("  in a spectrum given as input. Then the frequencies obtained in")
    print("  of these manners will be compared with those present in a selected")
    print("  spectroscopic database. This database (for the moment) should be")
    print("  given as an adittional input.")
    print()
    print("OPTION 4: REMOVE LINES FROM SPECTRUM")
    print("This script is ")
    print()
    print()
    print("OPTION 5: CHIRALITY MODE")
    print("This script has been coded for working with chiral taggin experiments.")
    print("In those experiments a chiral tag is introduced with the sample to")
    print("generate diasteroisomeric complexes that can be diferenciated by")
    print("rotational spectroscopy (shotout here to Yungie Xu, Brooks Pate and")
    print("other spectroscopist working on this technique). This script will take")
    print("the spectrum of the chiral tag, the sample and the final (mixed)")
    print("spectrum to clear any peak from sample and tag, easing the analysis of")
    print("the spectrum, as long as the final spectrum will only contain those")
    print("signals of the complexes. ")
    print()
    print("********************************************************************")
    print()
